management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8087
  tomcat:
    threads:
      max: 1000


dubbo:
  cloud:
    subscribed-services: user-servie
  registry:
    #address: nacos://192.168.43.176:8848
    address: nacos://47.113.100.78:8848
    check: false
  protocols:
    dubbo:
      prot: -1

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.113.100.78:8848
      #server-addr: 127.0.0.1:8848
      #server-addr: 192.168.43.176:8848




