server:
  port: 8090

#dubbo:
#  # 配置服务信息
#  application:
#    name: other-gateway
#    # 禁用QOS同一台机器可能会有端口冲突现象
#    qos-enable: false
#    qos-accept-foreign-ip: false
#  # 配置注册中心
#  registry:
#    address: nacos://172.16.0.18:8848
#  # 设置协议-协议由提供方指定消费方被动接受
#  protocol:
#    name: dubbo
#    port: -1
#    # 设置超时时间
#  consumer:
#    timeout: 4000
#    check: false
spring:
  application:
    name: order-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
      routes:
        - id: order
          uri: http://localhost:8086/
          predicates:
            - Path=/orders,/orders/states,/orders/{id},/orders/{id}/confirm,/shops/{shopId}/orders,/shops/{shopId}/orders/{id},/shops/{shopId}/orders/{id}/deliver
          filters:
            - PrefixPath=/order
            - Auth=authorization
        - id: freight
          uri: http://localhost:8083/
          predicates:
            - Path=/region/{rid}/price,/shops/{id}/freightmodels,/shops/{shopId}/freightmodels/{id}/**,/shops/{shopId}/weightItems/**,/shops/{shopId}/pieceItems/**
          filters:
            - PrefixPath=/freight
            - Auth=authorization
        - id: payment
          uri: http://localhost:8085/
          predicates:
            - Path=/payments/**,/orders/{id}/payments,/shops/{shopId}/orders/{id}/payments,/aftersales/{id}/**,/shops/{shopId}/aftersales/{id}/**,/shops/{shopId}/payments/{id}/**,/shops/{shopId}/orders/{id}/refunds,/orders/{id}/refunds,/aftersales/{id}/refunds
          filters:
            - PrefixPath=/payment
            - Auth=authorization

              #包含不需要token的路径
        - id: users-nonAuth
          uri: http://localhost:8082/
          predicates:
            - Path=/users, /users/login, /users/password/**
          filters:
            - PrefixPath=/user
        #包含需要token的路径
        - id: users
          uri: http://localhost:8082/
          predicates:
            - Path=/users/states, /users/all, users/logout, /users/{id}/**
          filters:
            - PrefixPath=/user
            - Auth=authorization


management:
  endpoint:
    gateway:
      enabled: true

## 配置rocketmq
#rocketmq:
#  # 指定namesrv地址
#  name-server: 47.115.162.144:9876
#  producer:
#    #生产者group名称
#    group: producer_group
#    #一次发送多少数量消息
#    max-message-size: 4096
#    #发送消息超时时间,默认3000
#    send-message-timeout: 3000
#    #发送消息失败重试次数，默认2
#    retry-times-when-send-async-failed: 2
#
## 网关token相关配置
gateway:
  jwtExpire: 3600
  refreshJwtTime: 60