
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oomall?serverTimezone=GMT%2B8
    username: dbuser
    password: 123456
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        enabled: true
        url-pattern: /druid/*
  redis:
    # Redis服务器地址
    #host: localhost
    host: 185.255.130.76
    # Redis服务器连接端口
    port: 15379
    # Redis服务器连接密码
    password: 123456

  cloud:
    nacos:
      discovery:
        #server-addr: 192.168.43.123:8848
        server-addr: 47.113.100.78
        #server-addr: 127.0.0.1:8848